name: Local Markets TESTING
on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to Checkout'
        required: true
        default: 'main'
      crosswords_branch:
        description: 'Crosswords Branch to Checkout'
        required: true
        default: 'main'
        
jobs:
  bundle:
    name: Build Local Bundles
    runs-on: ubuntu-latest
    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'

    steps:
      - name: Checkout jfdchatter
#         with:
#           path: native-apps-android
        run: |
          pwd
          echo "hello" > file.txt
          ls -a

      - name: Android Secret Files
        working-directory: /jfdchatter
        env:
          SYSTEM_HOME: /home/runner/work/jfdchatter/jfdchatter
        run: |
          pwd
          ls -a
