name: Tagging test

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Set up the version number
        run: |
          # echo "version_number=2.0.0" >> $GITHUB_ENV
          VNTEMP=$(grep GNT_SHORT VersionNumber.xcconfig | sed s/GNT_SHORT_VERSION_BASE=//g)
          VN=$VNTEMP.${{ github.run_number }}
          echo "version_number=$VN" >> $GITHUB_ENV

      - name: Run a one-line script
        run: echo Hello, world!

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.

      - name: Create tag
        uses: actions/github-script@v3
        with:
#           github-token: ${{ github.token }}
          script: |
            # const thetag = '${{ env.version_number }}
            github.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: "refs/tags/${{ env.version_number }}",
              sha: context.sha
            })
