name: Var Testing

on:
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Run a one-line script
        run: |
          version="1.0"
          echo $version
        
      - name: Run a multi-line script
        run: |
          echo $version
          echo 'did it keep?'
