# This is a basic workflow to help you get started with Actions

name: Slack test

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
#       - name: Run a multi-line script
#         run: |
          
#           JSON_PAYLOAD='{"channel":"ios-ci","attachments":[{"text":"hello, world"}]}'
          
#           curl -s -X POST -H "Authorization: Bearer ${{ secrets.SLACK_TOKEN }}" \
#           -H "Content-type: application/json" \
#           --data "$JSON_PAYLOAD" ${{ secrets.SLACK_WEBHOOK }}
          
#       - name: On Success
#         uses: rtCamp/action-slack-notify@v2
#         env:
#           SLACK_CHANNEL: ios-ci
#           SLACK_COLOR: good
#           SLACK_ICON: https://www.gannett.com/wp-content/uploads/2019/11/vendor_icon-150x150.png
#           SLACK_MESSAGE: (market) built successfully${{ github.run_number }}
#           SLACK_TITLE: Successful build example
#           SLACK_USERNAME: native-apps-ios
#           SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}


#       - name: On failure example
#         uses: rtCamp/action-slack-notify@v2
#         env:
#           SLACK_CHANNEL: ios-ci
#           SLACK_COLOR: bad
#           SLACK_ICON: https://www.gannett.com/wp-content/plugins/gannett-shortcodes//assets/icons_flat_announce.png
#           SLACK_MESSAGE: (market) failed to build. 
#           SLACK_TITLE: Build failed example, sorry ${{ github.actor }}          
#           SLACK_USERNAME: native-apps-ios
#           SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
